name: Translate README to EN version

on:
  repository_dispatch:
    types: [translate-readme-en]

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: English Translation
        run: cp en/README.md README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add README.md
          git commit -m "README atualizado para versão em inglês"
          git push
